apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "5s"
      httpMethod: "GET"
      exemplarTraceIdDestinations:
        - name: "trace_id"
          datasourceUid: "prometheus"
    secureJsonData: {}
    uid: "prometheus"