version: '3.8'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
      - ./data:/data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    restart: unless-stopped