FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements_exporter.txt .
RUN pip install --no-cache-dir -r requirements_exporter.txt

# Copy application code
COPY prometheus_exporter.py .

EXPOSE 8000

CMD ["python", "prometheus_exporter.py"]